### PR TITLE
Update SDK

### PR DESCRIPTION
**Pull request by andrewhancox**

### CODE REVIEW

**Comment by dmitriim** [comment]
Hi @andrewhancox 
Is it different to https://github.com/catalyst/moodle-local_aws/pull/33 ?

**Comment by andrewhancox** [comment]
Yes, it's a newer version.

**Comment by anton-catalyst-eu** [comment]
Hi all, happy Friday! Any chance this could be merged in please? It would fix a bunch of deprecation warnings we're getting during compatibility check with PHP 8. Many thanks in advance!

**Comment by golenkovm** [comment]
There have been a lot of newer changes. I will go ahead and close it off. Please refer to https://github.com/catalyst/moodle-local_aws/pull/67

**Pull request closed without merging**
